from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QSize, QObject
from PyQt5.QtWidgets import QDialog, QStyle, QTableView

from boatswain.common.models.container import Container
from boatswain.common.services import system_service
from boatswain.common.services.system_service import rt, applyFontRatio
from boatswain.common.ui.custom_ui import BQSizePolicy


class LoggingMonitorUi(QObject):
    def __init__(self, dialog: QDialog, container: Container) -> None:
        super().__init__()
        height = system_service.screen_height / 2
        width = height * 2
        dialog.resize(width, height)
        dialog.setSizePolicy(BQSizePolicy(h_stretch=1))
        dialog.setMinimumSize(QSize(width, height))
        dialog.setSizeGripEnabled(False)
        dialog.setModal(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.top_widget = QtWidgets.QWidget(dialog)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.top_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.tool_widget = QtWidgets.QWidget(self.top_widget)
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tool_widget)
        self.horizontalLayout.setContentsMargins(rt(12), rt(6), rt(12), rt(6))
        self.horizontalLayout.setSpacing(rt(6))
        self.now = QtWidgets.QPushButton(self.tool_widget)
        self.horizontalLayout.addWidget(self.now)
        self.hidden_1 = QtWidgets.QWidget(self.tool_widget)
        self.hidden_1.setSizePolicy(BQSizePolicy(h_stretch=1))
        self.horizontalLayout.addWidget(self.hidden_1)
        self.clear = QtWidgets.QPushButton(self.tool_widget)
        self.horizontalLayout.addWidget(self.clear)
        self.reload = QtWidgets.QPushButton(self.tool_widget)
        self.horizontalLayout.addWidget(self.reload)
        self.hidden_2 = QtWidgets.QWidget(self.tool_widget)
        self.hidden_2.setSizePolicy(BQSizePolicy(h_stretch=1))
        self.horizontalLayout.addWidget(self.hidden_2)
        self.info = QtWidgets.QPushButton(self.tool_widget)
        self.horizontalLayout.addWidget(self.info)
        self.hidden = QtWidgets.QWidget(self.tool_widget)
        self.horizontalLayout.addWidget(self.hidden)
        self.search = QtWidgets.QLineEdit(self.tool_widget)
        self.search.setSizePolicy(BQSizePolicy(h_stretch=3))
        self.horizontalLayout.addWidget(self.search)
        self.verticalLayout_2.addWidget(self.tool_widget)
        self.line = QtWidgets.QFrame(self.top_widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalLayout_2.addWidget(self.line)
        self.tags = QtWidgets.QWidget(self.top_widget)
        self.tags.setSizePolicy(BQSizePolicy(v_stretch=1))
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tags)
        self.horizontalLayout_2.setContentsMargins(rt(12), rt(2), 0, rt(4))
        self.horizontalLayout_2.setSpacing(rt(6))
        font = QtGui.QFont()
        font.setPointSize(applyFontRatio(10))
        self.container_name = QtWidgets.QToolButton(self.tags)
        self.container_name.setFont(font)
        self.container_name.setText(container.name)
        self.container_name.setIcon(dialog.style().standardIcon(getattr(QStyle, 'SP_FileIcon')))
        self.container_name.setStyleSheet("border: 0; border-radius: 2px")
        self.container_name.setCheckable(False)
        self.container_name.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.container_name.setArrowType(QtCore.Qt.NoArrow)
        self.horizontalLayout_2.addWidget(self.container_name)
        self.new_tag = QtWidgets.QLineEdit(self.tags)
        self.new_tag.setFont(font)
        self.new_tag.setStyleSheet("border: none; background-color: transparent")
        self.horizontalLayout_2.addWidget(self.new_tag)
        self.verticalLayout_2.addWidget(self.tags, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout.addWidget(self.top_widget)
        self.line_2 = QtWidgets.QFrame(dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.verticalLayout.addWidget(self.line_2)
        self.log_widget = QtWidgets.QWidget(dialog)
        self.log_widget.setSizePolicy(BQSizePolicy(v_stretch=3))
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.log_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(rt(6))
        self.log_list_table = QTableView(dialog)
        self.verticalLayout_3.addWidget(self.log_list_table)
        self.verticalLayout.addWidget(self.log_widget)

        self.retranslateUi()

    def retranslateUi(self):
        self.now.setText(self.tr("Now"))
        self.clear.setText(self.tr("Clear"))
        self.reload.setText(self.tr("Reload"))
        self.info.setText(self.tr("Info"))
        self.new_tag.setPlaceholderText(self.tr("New tag..."))